import { vi } from 'vitest';
import type { Mock } from 'vitest';
import type * as WebApiClient from '../../../ClientApp/src/api/web-api-client';

/**
 * Factory for the generated API clients.
 *
 * `ClientApp/src/api/web-api-client.ts` is generated by NSwag and is on the never-edit list, so it
 * is imported here for types only. Every client in it follows the same shape - construct, call
 * `setAuthToken(token)`, then call one or more request methods - which is the shape each test file
 * was hand-rolling:
 *
 * ```ts
 * RequestForQuoteClient: vi.fn(function RequestForQuoteClientMock() {
 *     return { setAuthToken: vi.fn(), getStepStatuses: vi.fn() };
 * })
 * ```
 *
 * Hand-rolling it per file means `setAuthToken` is a fresh mock in each one, so no test can assert
 * the token actually reached the client without wiring that up again by hand.
 */

export type ClientMethodMocks = Record<string, Mock>;

export interface ClientMock<TMethods extends ClientMethodMocks> {
    /** Drop-in replacement for the generated client class. */
    readonly constructor: Mock;
    /** The single instance every construction returns, so assertions survive re-renders. */
    readonly instance: TMethods & { setAuthToken: Mock };
    readonly setAuthToken: Mock;
    readonly methods: TMethods;
}

/**
 * Build a mock for one generated client.
 *
 * The same instance is returned from every construction. Components commonly build a new client per
 * effect run, and a per-construction instance would scatter call records across objects the test
 * never sees.
 */
export const createClientMock = <TMethods extends ClientMethodMocks>(
    methods: TMethods,
): ClientMock<TMethods> => {
    const setAuthToken = vi.fn();
    const instance = { setAuthToken, ...methods };
    const clientConstructor = vi.fn(function ClientMock() {
        return instance;
    });

    return { constructor: clientConstructor, instance, setAuthToken, methods };
};

/** Convenience for the common case: name the methods, get mocks for them. */
export const createClientMockFor = <TName extends string>(
    ...methodNames: readonly TName[]
): ClientMock<Record<TName, Mock>> => {
    const methods = Object.fromEntries(
        methodNames.map((name) => [name, vi.fn()]),
    ) as Record<TName, Mock>;

    return createClientMock(methods);
};

/**
 * Assemble a module mock for `web-api-client`, keeping every real export in place and replacing
 * only the named clients.
 *
 * Spreading the original matters: the module also exports the enums and DTO classes that components
 * compare against (`ApplicationType`, `PatternApprovalRequiredValues`, and so on). Replacing the
 * whole module with a bare object silently turns those into `undefined`, and the component then
 * fails an equality check for a reason that looks nothing like the cause.
 *
 * ```ts
 * vi.mock('../../../ClientApp/src/api/web-api-client', async (importOriginal) => {
 *     const { webApiClientModuleMock } = await import('../helpers/mockApiClient');
 *     return webApiClientModuleMock(await importOriginal(), { TypeApprovalClient: taClient });
 * });
 * ```
 */
export const webApiClientModuleMock = (
    original: typeof WebApiClient,
    clients: Record<string, ClientMock<ClientMethodMocks>>,
) => ({
    ...original,
    ...Object.fromEntries(
        Object.entries(clients).map(([name, client]) => [name, client.constructor]),
    ),
});

/** Reset every mock on a client between tests without rebuilding it. */
export const resetClientMock = (client: ClientMock<ClientMethodMocks>) => {
    client.constructor.mockClear();
    client.setAuthToken.mockReset();

    for (const method of Object.values(client.methods)) {
        method.mockReset();
    }
};
