import { DashboardItemStatus, QuoteStatus } from '../routes/common/enums';
import type { DashboardItemDto, LookupResponse, RequestForQuoteDetails } from '../api/web-api-client';

export const dashboardItems: DashboardItemDto[] = [
    {
        referenceId: 'RFQ-2024-001234',
        status: DashboardItemStatus.QuoteDrafted,
        requestedFor: 'Storybook Organisation',
        lastUpdated: new Date('2024-03-15'),
        requestForQuote: {
            id: 1,
            manufacturer: 'Fluke',
            model: '87V',
            serialNumber: 'SN123456',
            measurementCategory: 'Electrical',
            artefactType: 'Multimeter',
            requestSubmitted: new Date('2024-03-15'),
            contactDetails: {
                firstName: 'Taylor',
                lastName: 'Nguyen',
                email: 'taylor.nguyen@example.com',
                businessPhone: '02 1234 5678',
            },
            hideFromDashboard: false,
        },
    },
    {
        referenceId: 'RFQ-2024-000892',
        status: DashboardItemStatus.QuoteAvailable,
        requestedFor: 'Storybook Organisation',
        lastUpdated: new Date('2024-02-20'),
        requestForQuote: {
            id: 2,
            manufacturer: 'Keysight',
            model: 'U1242C',
            serialNumber: 'MY12345678',
            measurementCategory: 'Electrical',
            artefactType: 'Handheld Multimeter',
            requestSubmitted: new Date('2024-01-10'),
            contactDetails: {
                firstName: 'Taylor',
                lastName: 'Nguyen',
                email: 'taylor.nguyen@example.com',
                businessPhone: '02 1234 5678',
            },
            hideFromDashboard: false,
        },
        quote: {
            quotationId: 'Q-2024-000456',
            artefactName: 'Keysight U1242C Handheld Multimeter',
            dateRequired: new Date('2024-03-01'),
            offerDate: new Date('2024-02-20'),
            validUntil: new Date('2024-04-20'),
            nmiContactDetails: {
                firstName: 'NMI',
                lastName: 'Officer',
                email: 'nmi@industry.gov.au',
                businessPhone: '02 6213 6800',
            },
        },
    },
    {
        referenceId: 'RFQ-2023-009012',
        status: DashboardItemStatus.ReportIssued,
        requestedFor: 'Storybook Organisation',
        lastUpdated: new Date('2023-11-28'),
        requestForQuote: {
            id: 3,
            manufacturer: 'Mettler Toledo',
            model: 'XPE205',
            serialNumber: 'B123456789',
            measurementCategory: 'Mass',
            artefactType: 'Analytical Balance',
            requestSubmitted: new Date('2023-09-01'),
            contactDetails: {
                firstName: 'Taylor',
                lastName: 'Nguyen',
                email: 'taylor.nguyen@example.com',
                businessPhone: '02 1234 5678',
            },
            hideFromDashboard: false,
        },
        quote: {
            quotationId: 'Q-2023-007777',
            artefactName: 'Mettler Toledo XPE205 Analytical Balance',
            dateRequired: new Date('2023-09-15'),
            offerDate: new Date('2023-09-10'),
            validUntil: new Date('2023-11-10'),
            nmiContactDetails: {
                firstName: 'NMI',
                lastName: 'Officer',
                email: 'nmi@industry.gov.au',
                businessPhone: '02 6213 6800',
            },
        },
        report: {
            reportId: 'NMI/T/C/12345',
            invoiceNumber: 'INV-2023-009012',
            dateRequired: new Date('2023-09-15'),
            dateReceived: new Date('2023-09-16'),
            dateIssued: new Date('2023-11-25'),
            targetReportDate: new Date('2023-11-28'),
            returnMethod: 'Courier',
            dateDispatched: new Date('2023-11-28'),
            carrier: 'TNT',
            consignmentNote: 'CON123456789',
        },
    },
];

export const lookupResponses: LookupResponse[] = [
    { id: 'electrical', label: 'Electrical' },
    { id: 'mass', label: 'Mass' },
    { id: 'no-measurement', label: 'No measurement category available' },
];

export const artefactTypeResponses: LookupResponse[] = [
    { id: 'digital-thermometer', label: 'Digital thermometer', parentId: 'electrical' },
    { id: 'multimeter', label: 'Handheld multimeter', parentId: 'electrical' },
    { id: 'balance', label: 'Analytical balance', parentId: 'mass' },
    { id: 'no-instrument', label: 'No instrument/artefact type available', parentId: 'no-measurement' },
];

export const requestForQuoteDetailsFixture = {
    quoteRequestIdNum: 'RFQ-2024-000892',
    quotationIdNum: 'Q-2024-000456',
    quoteRequestStatus: QuoteStatus.QuoteAvailable,
    quotationOfferDate: new Date('2024-02-20'),
    quotationValidUntil: new Date('2024-04-20'),
    dateInstrumentRequiredNMI: new Date('2024-05-10'),
    targetDateMesurementReport: new Date('2024-06-20'),
    outcomeDate: new Date('2024-02-20'),
    serialNumber: 'MY12345678',
    manufacturer: 'Keysight',
    model: 'U1242C',
    description: 'Handheld multimeter used for field verification and annual compliance checks.',
    instrumentArtefactToBeCalibrated: 'Keysight U1242C handheld multimeter',
    servicesOffered: 'Calibration at 100 V, 230 V, 10 A and resistance points.',
    measurementReportCertificateRequired: 'Measurement report only',
    specialConditions: 'Return by client courier with protective packaging.',
    feePayableAmount: 1240.55,
    nmiTestOfficerName: 'Jordan Officer',
    nmiTestOfficerPhone: '02 6213 6800',
    nmiTestOfficerEmail: 'jordan.officer@industry.gov.au',
    nmiFacilityName: 'Lindfield Laboratory',
    nmiFacilityAddress: '36 Bradfield Road, Lindfield NSW 2070',
    nmiFacilityDeliveryInstructions: 'Deliver to receiving dock between 8:30am and 3:30pm.',
    receiptandDispatchNA: false,
    report: {
        reportId: 'NMI/T/C/12345',
        dateIssued: new Date('2024-06-18'),
        invoiceNumber: 'INV-2024-00999',
        dateDispatched: new Date('2024-06-19'),
        consignmentNote: 'CON-445566',
    },
    returnContactName: 'Taylor Nguyen',
    returnContactEmail: 'taylor.nguyen@example.com',
    returnOrganisationName: 'Storybook Organisation',
    returnAddressLine1: '100 Example Street',
    returnAddressSuburb: 'Canberra',
    returnAddressState: 'ACT',
    returnAddressPostcode: '2601',
    returnMethod: 'Courier',
    carrierName: 'TNT',
    carrierShipRef: 'REF-778899',
    carrierContactName: 'Dispatch Team',
    carrierContactPhone: '02 7000 0000',
} as RequestForQuoteDetails;
